In [1]:
import pandas as pd

In [2]:
filename = '/Users/niki/Documents/255_final_project/ESC-50-master/esc50-human.xlsx'
xl_file = pd.ExcelFile(filename, header = True)
audio_data = xl_file.parse('Raw data')
#audio_data.columns = ['label','audio_file']
audio_data.head()

  CLASS_NAME        X_AUDIO  Y_CLASS
0   Airplane  1-11687-A.ogg        1
1   Airplane  1-24796-A.ogg        1
2   Airplane  1-36929-A.ogg        1
3   Airplane  1-43807-A.ogg        1
4   Airplane  1-43807-B.ogg        1

In [3]:
#removed = original.replace("M", "")
audio_list = []
for name in audio_data.X_AUDIO:
    #print(name)
    new_name = name.replace(".ogg","")
    #print(new_name)
    audio_list.append(new_name)
    
audio_data["X_audio1"]=pd.DataFrame(audio_list)
audio_data.head()

  CLASS_NAME        X_AUDIO  Y_CLASS   X_audio1
0   Airplane  1-11687-A.ogg        1  1-11687-A
1   Airplane  1-24796-A.ogg        1  1-24796-A
2   Airplane  1-36929-A.ogg        1  1-36929-A
3   Airplane  1-43807-A.ogg        1  1-43807-A
4   Airplane  1-43807-B.ogg        1  1-43807-B

In [4]:
import os

path = '/Users/niki/Documents/255_final_project/ESC-50-master/audio/'
audio_files = []

for filename in os.listdir(path):
    audio_files.append(filename)
#audio_files

In [5]:
keyboard = []
for j in audio_data['X_audio1']:
    for name in audio_files:
        if j in name:
            keyboard.append(name)

#print(keyboard)
audio_data["audio_files"]=pd.DataFrame(keyboard)


# audio_data.drop("X_AUDIO", axis=1, inplace=True)

audio_data.drop("X_audio1", axis=1, inplace=True)
audio_data.head()

  CLASS_NAME        X_AUDIO  Y_CLASS       audio_files
0   Airplane  1-11687-A.ogg        1  1-11687-A-47.wav
1   Airplane  1-24796-A.ogg        1  1-24796-A-47.wav
2   Airplane  1-36929-A.ogg        1  1-36929-A-47.wav
3   Airplane  1-43807-A.ogg        1  1-43807-A-47.wav
4   Airplane  1-43807-B.ogg        1  1-43807-B-47.wav

In [6]:
from __future__ import print_function
import pandas as pd
import numpy as np

# matplotlib for displaying the output
import matplotlib.pyplot as plt
import matplotlib.style as ms
ms.use('seaborn-muted')
%matplotlib inline

# and IPython.display for audio output
from IPython.display import Audio
# Librosa for audio
import librosa
# And the display module for visualization
import librosa.display

In [ ]:
#i=0

x =path + str(audio_data['audio_files'][0])
y, sr = librosa.load(x)
f2=librosa.feature.zero_crossing_rate(y, frame_length=2048, hop_length=512, center=True)
log_f2 = pd.DataFrame(librosa.power_to_db(f2, ref=np.max))
d4=pd.DataFrame(log_f2)
print(sr)

In [7]:
def extract_feature(X):
    stft = np.abs(librosa.stft(X))
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=22050, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=22050).T,axis=0)
    mel = np.mean(librosa.feature.melspectrogram(X, sr=22050).T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=22050).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=22050).T,axis=0)
    return mfccs,chroma,mel,contrast,tonnetz

In [ ]:
features1 = np.empty((0,193))

x1 =path + str(audio_data['audio_files'][3938])
y1, sr1 = librosa.load(x1)
mfccs, chroma, mel, contrast,tonnetz = extract_feature(y1)
ext_features = np.hstack([mfccs,chroma,mel,contrast,tonnetz])
features1 = np.vstack([features1,ext_features])
print(features1)
#     X_1=pd.DataFrame(features[0])
#     audio = pd.concat([audio,X_1], axis=1)
#     f3=librosa.feature.zero_crossing_rate(y1, frame_length=2048, hop_length=512, center=True)
#     log_f3 = pd.DataFrame(librosa.power_to_db(f3, ref=np.max))
#     d4=pd.concat([d4,log_f3],axis=0)

In [ ]:
for i in range(1,len(audio_data)):
    x1 = path + str(audio_data['audio_files'][i])
    print(y1,sr1)
    y1, sr1 = librosa.load(x1)
    f3=librosa.feature.zero_crossing_rate(y1, frame_length=2048, hop_length=512, center=True)
    log_f3 = pd.DataFrame(librosa.power_to_db(f3, ref=np.max))
    d4=pd.concat([d4,log_f3],axis=0)
    break

In [23]:
features= np.empty((0,193))
audio=pd.DataFrame()

for i in range(1,len(audio_data)):
    x1 =path + str(audio_data['audio_files'][i])
    y1, sr1 = librosa.load(x1)
    mfccs, chroma, mel, contrast,tonnetz = extract_feature(y1)
    ext_features = np.hstack([mfccs,chroma,mel,contrast,tonnetz])
    features = np.vstack([features,ext_features])
    X_1=pd.DataFrame(features[i-1])
    audio = pd.concat([audio,X_1], axis=1)
#     f3=librosa.feature.zero_crossing_rate(y1, frame_length=2048, hop_length=512, center=True)
#     log_f3 = pd.DataFrame(librosa.power_to_db(f3, ref=np.max))
#     d4=pd.concat([d4,log_f3],axis=0)

/Applications/anaconda3/lib/python3.6/site-packages/librosa/core/pitch.py:145: UserWarning: Trying to estimate tuning from empty frequency set.
  warnings.warn('Trying to estimate tuning from empty frequency set.')

In [24]:
audio = audio.T

In [25]:
audio.shape

(3938, 193)

In [28]:
audio[0:20]

,0,1,2,3,4,5,6,7,8,9,...,183,184,185,186,187,188,189,190,191,192
0,33.770417,65.910975,-13.444122,26.475835,-13.347546,18.703846,-7.632413,5.946102,-5.707617,3.207748,...,13.534903,15.872428,15.481955,36.859761,0.004123,0.003098,0.004284,-0.014911,-0.002921,0.004836
0,-129.389497,189.934142,-44.292343,85.539574,11.651099,-30.926885,19.523379,-18.853259,-15.265460,-4.500389,...,15.682293,15.180072,30.046711,29.741746,0.072795,-0.030562,0.097074,0.182872,-0.034569,-0.019081
0,-166.700574,216.815158,-30.085475,48.000982,-6.999751,15.864524,9.544540,-9.050040,11.079670,0.042482,...,18.065899,18.426980,20.420488,33.505004,0.037429,0.036525,-0.001540,-0.151592,-0.026846,0.002937
0,-327.604394,241.768066,14.096161,17.600246,13.368117,19.212025,9.755920,-0.013697,12.047137,0.587287,...,15.331221,20.144520,16.926468,29.066962,-0.024309,0.039608,-0.039100,0.051495,0.006983,0.036107
0,-358.275990,234.839939,27.269591,18.512314,2.619101,15.385141,10.130532,-6.265298,2.760841,8.271427,...,15.537095,19.488285,17.458624,29.124377,0.010601,0.017586,-0.015944,0.018130,0.004023,-0.006993
0,-358.275990,234.839939,27.269591,18.512314,2.619101,15.385141,10.130532,-6.265298,2.760841,8.271427,...,15.537095,19.488285,17.458624,29.124377,0.010601,0.017586,-0.015944,0.018130,0.004023,-0.006993
0,-225.506925,225.550447,0.994303,33.063173,10.846359,11.171191,12.081479,0.696198,3.887465,0.926074,...,16.031111,17.157639,18.742328,31.462581,-0.017363,0.010442,-0.098530,0.083072,0.015098,0.023622
0,-225.506925,225.550447,0.994303,33.063173,10.846359,11.171191,12.081479,0.696198,3.887465,0.926074,...,16.031111,17.157639,18.742328,31.462581,-0.017363,0.010442,-0.098530,0.083072,0.015098,0.023622
0,-192.352273,175.627714,-33.676074,55.184188,9.914897,9.499401,14.152022,6.548122,2.751026,7.011328,...,14.547534,15.276453,21.299395,31.865935,-0.003899,-0.012048,-0.076130,0.008884,-0.002478,0.001120
0,-192.352273,175.627714,-33.676074,55.184188,9.914897,9.499401,14.152022,6.548122,2.751026,7.011328,...,14.547534,15.276453,21.299395,31.865935,-0.003899,-0.012048,-0.076130,0.008884,-0.002478,0.001120
0,-411.182222,168.403346,21.638055,26.417979,-2.180694,28.460969,3.992510,8.361559,1.596783,8.310629,...,14.751463,16.558727,14.044870,32.832032,0.050957,-0.025213,-0.022366,0.252353,0.048288,-0.041130
0,-411.182222,168.403346,21.638055,26.417979,-2.180694,28.460969,3.992510,8.361559,1.596783,8.310629,...,14.751463,16.558727,14.044870,32.832032,0.050957,-0.025213,-0.022366,0.252353,0.048288,-0.041130
0,-104.682978,195.013283,-35.603523,-14.726885,-6.995800,-9.155637,-23.776757,-3.633209,-14.986913,-3.963134,...,15.652261,20.240628,17.146255,33.422131,-0.013377,0.000090,-0.009990,0.046838,0.002225,-0.016276
0,-104.682978,195.013283,-35.603523,-14.726885,-6.995800,-9.155637,-23.776757,-3.633209,-14.986913,-3.963134,...,15.652261,20.240628,17.146255,33.422131,-0.013377,0.000090,-0.009990,0.046838,0.002225,-0.016276
0,-119.868333,170.738460,-16.338515,39.474895,6.616226,18.176469,10.953986,8.284317,7.933917,15.086913,...,14.275895,15.554397,18.090393,34.015890,-0.010980,-0.014231,-0.026899,-0.049287,-0.007130,0.020817
0,-119.868333,170.738460,-16.338515,39.474895,6.616226,18.176469,10.953986,8.284317,7.933917,15.086913,...,14.275895,15.554397,18.090393,34.015890,-0.010980,-0.014231,-0.026899,-0.049287,-0.007130,0.020817
0,-119.868333,170.738460,-16.338515,39.474895,6.616226,18.176469,10.953986,8.284317,7.933917,15.086913,...,14.275895,15.554397,18.090393,34.015890,-0.010980,-0.014231,-0.026899,-0.049287,-0.007130,0.020817
0,-256.929029,227.457286,-44.489070,19.052841,41.229726,-2.876870,5.410659,8.287498,0.128924,3.937026,...,15.184293,20.127398,21.372571,26.763469,-0.001443,-0.001597,-0.029166,0.047939,-0.006874,0.001106
0,-256.929029,227.457286,-44.489070,19.052841,41.229726,-2.876870,5.410659,8.287498,0.128924,3.937026,...,15.184293,20.127398,21.372571,26.763469,-0.001443,-0.001597,-0.029166,0.047939,-0.006874,0.001106
0,-104.483694,120.523639,-15.961659,12.244503,-6.209773,23.253767,26.769890,20.883162,15.324390,5.931239,...,16.486669,15.252534,16.566255,30.489337,-0.028895,-0.015618,0.031072,0.007259,0.006021,0.015020

In [ ]:
audio.head()

In [ ]:
d4.to_csv('/Users/niki/Documents/255_final_project/ESC-50-master/inputaudioFeatures.csv')

In [ ]:
d4 = d4.reset_index(drop=True)

In [ ]:
d4.head()

In [ ]:
#j = 0
new_audio = pd.DataFrame(audio_data.iloc[[0]])
audio_feature = pd.DataFrame(d4.iloc[[0]])

final_data = pd.concat([new_audio,audio_feature],axis=1)
final_data

In [ ]:
for j in range(1,len(audio_data)):
    new_audio1 = pd.DataFrame(audio_data.iloc[[j]])
    audio_feature1 = pd.DataFrame(d4.iloc[[j]])

    final_data1 = pd.concat([new_audio1,audio_feature1],axis=1)
    final_data = pd.concat([final_data , final_data1], axis=0)

In [ ]:
final_data.head()

In [ ]:
final_data.to_csv('/Users/niki/Documents/255_final_project/ESC-50-master/entire_file.csv')